from os.path import join as pjoin
import sys

# rule get_cats_keep_to_check:
#     input: CAT_CLASSIFICATION, ICA_PAPER_DF
#     output: CATS_KEEP_TO_CHECK
#     shell: "python scripts/get_cats_keep_to_check.py {input} {output}"

# rule get_ica_author_df:
#     input: ICA_PAPER_DF
#     output: ICA_AUTHOR_DF, NO_AUTHOR_URLS
#     shell: "python scripts/get_ica_author_df.py {input} {output}"

DATA_DIR = "../data/"
RAW_DATA_DIR = pjoin(DATA_DIR, "raw")
RAW_LARGE_DATA_DIR = pjoin(RAW_DATA_DIR, 'large')
INTERIM_DATA_DIR = pjoin(DATA_DIR, "interim")
INTERIM_LARGE_DATA_DIR = pjoin(INTERIM_DATA_DIR, 'large')
PROCESSED_DATA_DIR = pjoin(DATA_DIR, "processed")

###############################################################################
# Raw Data
###############################################################################

# SSCI journals 
SSCI = pjoin(RAW_DATA_DIR, 'ssci.csv')

ROR_RAW_DATA = pjoin(RAW_LARGE_DATA_DIR, 'ror.json')

###############################################################################
# Interim outputs
###############################################################################

ICA_PAPER_DF = pjoin(INTERIM_DATA_DIR, 'ica_paper_df.csv')

ICA_PAPER_DATA = pjoin(INTERIM_DATA_DIR, 'ica_paper_data.csv')
ICA_AUTHOR_DATA = pjoin(INTERIM_DATA_DIR, 'ica_author_data.csv')
ICA_ERROR_URLS = pjoin(INTERIM_DATA_DIR, 'ica_error_urls.txt')

ICA_AUTHOR_DF = pjoin(INTERIM_DATA_DIR, 'ica_author_df.csv')
NO_AUTHOR_URLS = pjoin(INTERIM_DATA_DIR, 'no_author_urls.txt')

AUTHOR_WITH_GENDER = pjoin(INTERIM_DATA_DIR, 'author_with_gender.csv')

AUTHOR_WITH_PRED_RAW = pjoin(INTERIM_DATA_DIR, 'author_with_pred_raw.csv')

CAT_CLASSIFICATION = pjoin(INTERIM_DATA_DIR, 'cat_classification.csv')
# DOIS_TO_DELETE = pjoin(INTERIM_DATA_DIR, 'dois_to_delete.txt')
# DOIS_TO_KEEP = pjoin(INTERIM_DATA_DIR, 'dois_to_keep.txt')

CATS_KEEP_TO_CHECK = pjoin(INTERIM_DATA_DIR, 'cats_keep_to_check.csv')

ICR_RAW_DATA = pjoin(INTERIM_DATA_DIR, 'icr_raw_data.csv')

###############################################################################
# Processed outputs
###############################################################################

AUTHOR_WITH_PRED = pjoin(PROCESSED_DATA_DIR, 'author_with_pred.csv')
ICA_PAPER_DF_WITH_TYPE = pjoin(PROCESSED_DATA_DIR, 'ica_paper_df_with_type.csv')
RESEARCH_AUTHOR_WITH_PRED = pjoin(PROCESSED_DATA_DIR, 'research_author_with_pred.csv')

RANDOM_ISSUES = pjoin(PROCESSED_DATA_DIR, 'random_issues.txt')

###############################################################################
# Workflows
###############################################################################

rule all:
    input:
        ICA_PAPER_DF,
        # ICA_AUTHOR_DF,
        # NO_AUTHOR_URLS, 
        ICA_PAPER_DATA,
        ICA_AUTHOR_DATA,
        ICA_ERROR_URLS,
        AUTHOR_WITH_GENDER,
        AUTHOR_WITH_PRED_RAW,
        AUTHOR_WITH_PRED,       
        CATS_KEEP_TO_CHECK,
        ICA_PAPER_DF_WITH_TYPE,
        RESEARCH_AUTHOR_WITH_PRED,
        ICR_RAW_DATA,

# scrape ica paper dois
rule scrape_ica_paper_dois:
    output: ICA_PAPER_DF
    shell: "python scripts/scrape_ica_paper_dois.py {output}"

# scrape ica author and paper data
rule scrape_ica_author_data:
    input: ICA_PAPER_DF
    output: ICA_PAPER_DATA, ICA_AUTHOR_DATA, ICA_ERROR_URLS
    shell: "python scripts/scrape_ica_author_data.py {input} {output}"

# get author gender raw predictions
rule get_author_with_gender:
    input: ICA_AUTHOR_DATA, 
    output: AUTHOR_WITH_GENDER
    shell: "python scripts/get_author_with_gender.py {input} {output}"

# get race and affiliations. Raw because I'll change column order later
rule get_author_with_pred_raw:
    input: 
        AUTHOR_WITH_GENDER, 
        ROR_RAW_DATA
    output: AUTHOR_WITH_PRED_RAW
    shell: "python scripts/get_author_with_pred_raw.py {input} {output}"

# rearrange colomn order
rule get_author_with_pred:
    input: AUTHOR_WITH_PRED_RAW
    output: AUTHOR_WITH_PRED
    shell: "python scripts/get_author_with_pred.py {input} {output}"

rule get_research_paper_only:
    input: 
        CAT_CLASSIFICATION,
        DOIS_TO_DELETE,
        DOIS_TO_KEEP,
        ICA_PAPER_DF,
        AUTHOR_WITH_PRED,
    output: ICA_PAPER_DF_WITH_TYPE, RESEARCH_AUTHOR_WITH_PRED
    shell: "python scripts/get_research_paper_only.py {input} {output}"

rule get_icr_raw_data:
    input: RESEARCH_AUTHOR_WITH_PRED
    output: ICR_RAW_DATA
    shell: "python scripts/get_icr_raw_data.py {input} {output}"

