from os.path import join as pjoin
import sys

DATA_DIR = "../data/"
RAW_DATA_DIR = pjoin(DATA_DIR, "raw")
INTERIM_DATA_DIR = pjoin(DATA_DIR, "interim")
INTERIM_LARGE_DATA_DIR = pjoin(INTERIM_DATA_DIR, 'large')
PROCESSED_DATA_DIR = pjoin(DATA_DIR, "processed")

###############################################################################
# Raw Data
###############################################################################

# SSCI journals 
SSCI = pjoin(RAW_DATA_DIR, 'ssci.csv')

###############################################################################
# Interim outputs
###############################################################################

ICA_PAPER_DF = pjoin(INTERIM_DATA_DIR, 'ica_paper_df.csv')

ICA_PAPER_DATA = pjoin(INTERIM_DATA_DIR, 'ica_paper_data.csv')
ICA_AUTHOR_DATA = pjoin(INTERIM_DATA_DIR, 'ica_author_data.csv')
ICA_ERROR_URLS = pjoin(INTERIM_DATA_DIR, 'ica_error_urls.txt')

ICA_AUTHOR_DF = pjoin(INTERIM_DATA_DIR, 'ica_author_df.csv')
NO_AUTHOR_URLS = pjoin(INTERIM_DATA_DIR, 'no_author_urls.txt')

AUTHOR_WITH_PRED = pjoin(INTERIM_DATA_DIR, 'author_with_pred.csv')

###############################################################################
# Workflows
###############################################################################

rule all:
    input:
        ICA_PAPER_DF,
        # ICA_AUTHOR_DF,
        # NO_AUTHOR_URLS, 
        ICA_PAPER_DATA,
        ICA_AUTHOR_DATA,
        ICA_ERROR_URLS,
        AUTHOR_WITH_PRED,

rule scrape_ica_paper_dois:
    output: ICA_PAPER_DF
    shell: "python scripts/scrape_ica_paper_dois.py {output}"

rule get_ica_author_df:
    input: ICA_PAPER_DF
    output: ICA_AUTHOR_DF, NO_AUTHOR_URLS
    shell: "python scripts/get_ica_author_df.py {input} {output}"

rule scrape_ica_author_data:
    input: ICA_PAPER_DF
    output: ICA_PAPER_DATA, ICA_AUTHOR_DATA, ICA_ERROR_URLS
    shell: "python scripts/scrape_ica_author_data.py {input} {output}"

rule get_gender_race_aff_pred:
    input: ICA_AUTHOR_DATA
    output: AUTHOR_WITH_PRED
    shell: "python scripts/get_gender_race_aff_pred.py {input} {output}"

