---
title: "Citation Analysis"
output: pdf_document
---

```{r setup, include=FALSE}
library(car)
library(olsrr)
library(stargazer)
```

## Read data

The first step is to read data:

```{r read data}
df <- read.csv("../data/processed/papers_to_study_expanded.csv")
df$Year.Distance.from.2022 = abs(df$year - 2022)

# do the log10 transformation on citation counts
df$gscholar_citation_log10 <- log10(df$gscholar_citation + 0.1)
var_cols <- c(1, 16:17, 20:33, 35:36)
data <- df[, var_cols]
```

## Deal with univariate outliers

```{r}
hist(data$gscholar_citation_log10)
data$gscholar_citation_log10_stdized <- scale(
  data$gscholar_citation_log10,
  center = T,
  scale = T
)
data$outlier0 <- ifelse(data$gscholar_citation_log10_stdized > 3.3 | 
                          data$gscholar_citation_log10_stdized < -3.3,
                        1, 0
)
table(data$outlier0)
```

As can be seen, there are 124 outliers. 

## Build model

```{r}
datanew <- subset(data, outlier0 == 0)
datanew$outlier0 <- NULL
datanew$gscholar_citation_log10_stdized <- NULL

model <- lm(gscholar_citation_log10~., datanew)
```

## Dianostics

```{r}
## Normality
ols_plot_resid_qq(model)

#Correlation between observed residuals and expected residuals under normality.
ols_test_correlation(model)

ols_plot_resid_hist(model)

## linearity & homoscedasticity 
ols_plot_resid_fit(model)

## collinearity diagnostics
# ols_coll_diag(model)
vif(model)
```

## Run Model

```{r}
summary(model)
```
